spring:
  profiles:
    active: dev
  freemarker:
    enabled: true
    template-loader-path: classpath:/templates
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .ftl                #视图解析后缀
    prefer-file-system-access: false #不同模块的静态文件也能映射
    settings:
      number_format: 0.######
      classic_compatible: true    #防止报空指针
  jpa:
    database: default
    show-sql: true
    open-in-view: false
    hibernate:
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
  devtools:
      restart:
        enabled: true  #设置开启热部署
  jackson:
    time-zone: GMT+8    #时区
    date-format: yyyy-MM-dd HH:mm:ss    #JSON时间格式
  mvc:
    view:
      prefix: classpath:/templates  #springmvc视图解析前缀
    static-path-pattern: /static/**
    hiddenmethod:
      filter:
        #开启支持resful请求
        enabled: true
    date-format: yyyy-MM-dd
  activiti:
    #自动部署验证设置:true-开启（默认）、false-关闭
    check-process-definitions: false
    database-schema-update: true

debug: true
logging:
  level:
      org.springframework.boot.autoconfigure: warn
      org.activiti.engine.impl.persistence.entity: trace
      org.springframework.web: trace
  config: classpath:loggback.xml
server:
  max-http-header-size: 65546

# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice/*
  # 匹配链接
  urlPatterns: /*
aj:
  captcha:
    jigsaw: classpath:/captcha/images/jigsaw
    pic-click: classpath:/captcha/images/pic-click
    cache-type: local
    type: default
    water-mark: \u72ec\u914c\u5de5\u4f5c\u5ba4
    slip-offset: 5
    aes-status: true
    interference-options: 2
    history-data-clear-enable: true
    req-frequency-limit-enable: true
    req-get-lock-limit: 5
    req-get-lock-seconds: 360
    req-get-minute-limit: 30

