wan:
  profile:                      #项目文件配置
    file-path: D:/wan/uploadPath #默认文件下载路径
    max-size: 1MB        #文件最大限制
    max-file-name: 20      #文件名称最长限制

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: oracle.jdbc.OracleDriver
    druid:
      url: jdbc:oracle:thin:@localhost:1521:orcl
      username: scott
      password: root
      initial-size: 20
      min-idle: 20
      max-active: 30
      max-wait: 60000
  freemarker:
    enabled: true
    template-loader-path: classpath:/templates
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .ftl
    prefer-file-system-access: false #不同模块的静态文件也能映射
    settings:
      number_format: 0.######
  jpa:
    database: oracle
    show-sql: true
    open-in-view: false
  devtools:
      restart:
        enabled: true  #设置开启热部署
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  mvc:
    view:
      prefix: classpath:/templates/
    static-path-pattern: /**
    hiddenmethod:
      filter:
        enabled: true  #开启支持resful请求

  servlet:
    multipart:
      max-file-size: ${wan.profile.max-size}

server:
  port: 8082
  servlet:
    context-path: /
  tomcat:
    uri-encoding: utf-8
    max-threads: 500
logging:
  level:
    org.springframework.boot.autoconfigure: warn
    root: warn

  file:
    path: /
    name: wanlog.log

debug: true




