spring:
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: oracle.jdbc.OracleDriver
      jdbc-url: jdbc:oracle:thin:@localhost:1521:orcl
      username: scott
      password: root
      druid:
        initial-size: 20
        min-idle: 20
        max-active: 30
        max-wait: 60000
  mail:
    host: smtp.163.com
    username: why15079185135@163.com
    password: LSGGAYSGQKCBWNEK
    default-encoding: UTF-8
  servlet:
    multipart:
      max-file-size: ${wan.profile.max-size}
      max-request-size: 2MB
  redis:
    host: localhost
    port: 6379
    password:


wan:
  profile:                      #项目文件配置
    file-path: D:/wan/uploadPath  #默认文件存储路径
    file-virtual-Path: /upload    #文件储路径对应的项目虚拟路径
    file-virtual-Path-public: /upload/public #shiro 放行文件夹
    max-size: 1MB        #文件最大限制
    max-file-name: 40      #文件名称最长限制
    support-file-type: bmp,gif,jpg,jpeg,png,doc,docx,xls,xlsx,ppt,pptx,txt,rar,zip,pdf
  redis:
    shiro-time-out: 3600 #shiro redis缓存失效时间
  setting:
    name: springboot-wan
    email: 1434495271@qq.com
    err-msg-email-reminder: false
    cipher-key: 0RU6J7R8QhqqO1SE4oF1kA==

server:
  port: 8083    #端口号
  servlet:
    context-path: /
  tomcat:
    uri-encoding: utf-8
    max-threads: 500

#微信公众号开发
#教程https://mp.weixin.qq.com/debug?token=476802302&lang=zh_CN
#教程https://developers.weixin.qq.com/doc/offiaccount/OA_Web_Apps/Wechat_webpage_authorization.html
#注：通过appid和secret 获取access_token
#注：ip设置白名单，否则无法获取
# https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid=wxc64be930f85801c2&secret=59daaee2149a269e4def5aa1be898bf2
# access_token是公众号的凭证，有效期2小时，需要定时刷新
#
wan-oauth:
  wechart-appid: wx9e25e5433e58242a
  wechart-secret: eab3d7fc4002b849113ec1c4b2fc80bc
  wx-snsapi-base: snsapi_userinfo
  wx-state: STATE
  wx-connect-oath2-authorize-url: https://open.weixin.qq.com/connect/oauth2/authorize?appid=%s&redirect_uri=%s&response_type=code&scope=%s&state=%s&connect_redirect=1#wechat_redirect
  wx-get-token-url: https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid=APPID&secret=APPSECRET
  request-url: http://wanhongyuan.test.utools.club/api/wechat/userinfo
  user-token: https://api.weixin.qq.com/sns/oauth2/access_token?appid=APPID&secret=SECRET&code=CODE&grant_type=authorization_code
  user-info: https://api.weixin.qq.com/sns/userinfo?access_token=ACCESS_TOKEN&openid=OPENID&lang=zh_CN

