spring:
  profiles:
    active: dev
  freemarker:
    enabled: true
    template-loader-path: classpath:/templates
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .ftl                #视图解析后缀
    prefer-file-system-access: false #不同模块的静态文件也能映射
    settings:
      number_format: 0.######
  jpa:
    database: oracle
    show-sql: true
    open-in-view: false
  devtools:
      restart:
        enabled: true  #设置开启热部署
  jackson:
    time-zone: GMT+8    #时区
    date-format: yyyy-MM-dd HH:mm:ss    #JSON时间格式
  mvc:
    view:
      prefix: classpath:/templates  #springmvc视图解析前缀
    static-path-pattern: /static/**
    hiddenmethod:
      filter:
        #开启支持resful请求
        enabled: true
debug: true




